Traceback (most recent call last):
  File "F:\miniconda3\envs\py311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "F:\miniconda3\envs\py311\Lib\site-packages\nbclient\client.py", line 1304, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\miniconda3\envs\py311\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\miniconda3\envs\py311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\miniconda3\envs\py311\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "F:\miniconda3\envs\py311\Lib\site-packages\nbclient\client.py", line 1020, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "F:\miniconda3\envs\py311\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fName = input('What\'s Is Your First Name?')
mName = input('What\'s Is Your Middle Name?')
lName = input('What\'s Is Your Last Name?')

fName = fName.strip().capitalize()
mName = mName.strip().capitalize()
lName = lName.strip().capitalize()

print(f"Hello {fName} {mName:.1s} {lName} Happy To See You.")

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[211], line 1[0m
[1;32m----> 1[0m fName [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mWhat[39;49m[38;5;130;43;01m\'[39;49;00m[38;5;124;43ms Is Your First Name?[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m mName [38;5;241m=[39m [38;5;28minput[39m([38;5;124m'[39m[38;5;124mWhat[39m[38;5;130;01m\'[39;00m[38;5;124ms Is Your Middle Name?[39m[38;5;124m'[39m)
[0;32m      3[0m lName [38;5;241m=[39m [38;5;28minput[39m([38;5;124m'[39m[38;5;124mWhat[39m[38;5;130;01m\'[39;00m[38;5;124ms Is Your Last Name?[39m[38;5;124m'[39m)

File [1;32mF:\miniconda3\envs\py311\Lib\site-packages\ipykernel\kernelbase.py:1190[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1188[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m   1189[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m-> 1190[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[0;32m   1191[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1192[0m     [38;5;28mstr[39m(prompt),
[0;32m   1193[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1194[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1195[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1196[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

